# Generated by Django 4.1 on 2024-06-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PeopleBd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("firstName", models.CharField(max_length=25, verbose_name="Фамилия")),
                ("name", models.CharField(max_length=25, verbose_name="Имя")),
                ("lastName", models.CharField(max_length=25, verbose_name="Отчество")),
                ("dateofBurth", models.DateField(verbose_name="Дата рождения")),
                (
                    "passportIdNumber",
                    models.CharField(
                        max_length=15, verbose_name="Идентификационный номер паспорта"
                    ),
                ),
                (
                    "passportSeries",
                    models.CharField(max_length=10, verbose_name="Серия паспорта"),
                ),
            ],
        ),
    ]
