# Generated by Django 4.1 on 2024-06-19 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ListOfPeople", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="peoplebd",
            options={"verbose_name": "Человек", "verbose_name_plural": "Люди"},
        ),
        migrations.RenameField(
            model_name="peoplebd",
            old_name="dateofBurth",
            new_name="dateOfBirth",
        ),
    ]
