# Generated by Django 4.1 on 2024-06-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "ListOfPeople",
            "0004_individualbd_dateissuedby_individualbd_doctype_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="IndividEnter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "firstName",
                    models.CharField(max_length=25, null=True, verbose_name="Фамилия"),
                ),
                (
                    "name",
                    models.CharField(max_length=25, null=True, verbose_name="Имя"),
                ),
                (
                    "lastName",
                    models.CharField(max_length=25, null=True, verbose_name="Отчество"),
                ),
                (
                    "dateOfBirth",
                    models.DateField(null=True, verbose_name="Дата рождения"),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Место жительства"
                    ),
                ),
                (
                    "docType",
                    models.CharField(
                        max_length=20, null=True, verbose_name="Вид документа"
                    ),
                ),
                (
                    "passportIdNumber",
                    models.CharField(
                        max_length=15,
                        null=True,
                        verbose_name="Идентификационный номер паспорта",
                    ),
                ),
                (
                    "passportSeries",
                    models.CharField(
                        max_length=10, null=True, verbose_name="Серия паспорта"
                    ),
                ),
                (
                    "issuedBy",
                    models.CharField(
                        max_length=150, null=True, verbose_name="Кем выдан документ"
                    ),
                ),
                (
                    "dateIssuedBy",
                    models.DateField(null=True, verbose_name="Дата выдачи документа"),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Адрес электронной почты"
                    ),
                ),
                (
                    "numberPhone",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Номер телефона"
                    ),
                ),
                (
                    "numberStateRegist",
                    models.CharField(
                        max_length=20,
                        null=True,
                        verbose_name="Номер государственной регистрации",
                    ),
                ),
                (
                    "nameOfCompanyRegist",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="Наименование организации",
                    ),
                ),
                (
                    "dateRegist",
                    models.DateField(null=True, verbose_name="Дата регистрации"),
                ),
                (
                    "decisionNumber",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Номер решения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Индивидуальный предприниматель",
                "verbose_name_plural": "Индивидуальные предприниматели",
            },
        ),
        migrations.CreateModel(
            name="LegalPerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nameOfCompany",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Наименование организации",
                    ),
                ),
                (
                    "locationOfTheCompany",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Адрес организации"
                    ),
                ),
                (
                    "numberStateRegist",
                    models.CharField(
                        max_length=20,
                        null=True,
                        verbose_name="Номер государственной регистрации",
                    ),
                ),
                (
                    "nameOfCompanyRegist",
                    models.CharField(
                        max_length=50,
                        null=True,
                        verbose_name="Наименование организации",
                    ),
                ),
                (
                    "dateRegist",
                    models.DateField(null=True, verbose_name="Дата регистрации"),
                ),
                (
                    "decisionNumber",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Номер решения"
                    ),
                ),
                (
                    "payerAccNumber",
                    models.CharField(
                        max_length=20,
                        null=True,
                        verbose_name="Учетный номер плательщика",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=50, null=True, verbose_name="Адрес электронной почты"
                    ),
                ),
                (
                    "numberPhone",
                    models.CharField(
                        max_length=15, null=True, verbose_name="Контактный телефон"
                    ),
                ),
                (
                    "firstNameMan",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Фамилия руководителя"
                    ),
                ),
                (
                    "nameMan",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Имя руководителя"
                    ),
                ),
                (
                    "lastNameMan",
                    models.CharField(
                        max_length=25, null=True, verbose_name="Отчество руководителя"
                    ),
                ),
            ],
            options={
                "verbose_name": "Юридическое лицо",
                "verbose_name_plural": "Юридические лица",
            },
        ),
    ]
